#!/bin/bash

# 
# 概要: 左項値と右項値を演算した値を以下の形式で標準出力に出力する。
# 　　　<左項値> <演算子> <右項値> = <演算結果>
# 
# パラメータ: 
# 　なし
# 
# リターンコード: 
# 　正常終了時: 0
# 

# --- 定数定義 ---

# リターンコード: 成功
declare -ri RC_SUCCESS=0

# --- 関数定義 ---

# エラーを出力して終了する
# $1: エラーメッセージ
function error() {
    local -r message=$1
    echo "${message}">&2
}

# 値が期待した演算子かどうかを判定する
# $1: 値
function is_operator() {
    local -r value=$1
    [[ value =~ ^[+*/-]$ ]]
}

# 値が整数かどうかを判定する
# $1: 値
function is_integer() {
    local -r value=$1
    [[ value =~ ^[+-]?[0-9]+$ ]]
}

# ゼロ除算をしているかどうかを判定する
# $1: 値
function division_by_zero() {
    local -r value=$1
    [[ value =~ ^0+$ ]]
}

# 演算子の入力を求める
function input_operator() {
    local -r operator
    while :
        do
            read -p '演算子を入力してください (+ - * /): ' operator_inputed

            # 不正な演算子チェック
            if is_operator "${operator_inputed}"; then
                local -r operator=${operator_inputed}
                return
            else
                error "エラー: 不正な演算子が入力されました。"
            fi
        done
}

# 左項値の入力を求める
function input_left() {
    local -r left_inputed
    read -p '左項値を入力してください (整数): ' left_inputed

    if is_integer "${left_inputed}"; then
        local -r left_number=${left_inputed}
    else
        error "エラー: 整数以外の値が入力されました。"
        return
    fi
}

# 右項値の入力を求める
function input_right() {
    local -r right_inputed
    read -p '右項値を入力してください (整数): ' right_inputed

    if is_integer "${right_inputed}"; then
        local -r right_number=${right_inputed}
        # ゼロ除算チェック
        if ! division_by_zero "$1"; then
            error "エラー: ゼロで除算しようとしました。"
        fi
    else
        error "エラー: 整数以外の値が入力されました。"
        return
    fi
}

# 処理を継続するかを聞く。
# yesが入力されると処理が継続され、noが入力されるとループをぬける。
function continue_or_not() {
    local -r yes_or_no
    read -p '処理を継続しますか？ (yes/no): ' yes_or_no

    if [[ yes_or_no == "yes" ]]; then
        return
    elif [[ yes_or_no == "yes" ]]; then
        echo "処理を終了します。"
        break
    fi
}

# 以下のような出力形式で結果を出力する。
# <左項値> <演算子> <右項値> = <演算結果>
    function desplay_result() {
        local -r result

        case ${operator} in
            "+" ) result=$(( left + right ));;
            "-" ) result=$(( left - right ));;
            "*" ) result=$(( left * right ));;
            "/" ) result=$(( left / right ));;
        esac

        echo "${left}" "${operator}" "${right}" "=" "${result}"
    }

# --- 主処理 ---

while :
    do
        # 演算子
        input_operator
        # 左項値
        input_left
        # 右項値
        input_right
        # 結果を出力する
        desplay_result
        # 処理を継続するかを聞く
        continue_or_not
        break;
    done
exit ${RC_SUCCESS}